// Downloads the exact Google Fonts CSS the legacy page used (all unicode-range subsets, so
// glyphs like ← ♥ ♡ render identically) and rewrites it to self-hosted files.
// Fonts: Caveat, Fraunces, Nunito, Pixelify Sans — all SIL Open Font License 1.1.
// Run: node scripts/fetch-fonts.mjs   (output is committed; nothing is fetched at runtime)
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Caveat:wght@500;700&family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;1,9..144,400;1,9..144,600&family=Nunito:wght@500;700;800&family=Pixelify+Sans:wght@500;700&display=swap";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36";
const CSS_OUT = path.resolve("src/templates/scrapbook/fonts");
const OUT = path.resolve("public/fonts"); // stable URLs (/fonts/…) so pages can preload them

fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(CSS_OUT, { recursive: true });
let css = await (await fetch(CSS_URL, { headers: { "user-agent": UA } })).text();
const urls = [...new Set([...css.matchAll(/url\((https:[^)]+)\)/g)].map((m) => m[1]))];
for (const u of urls) {
  const buf = Buffer.from(await (await fetch(u, { headers: { "user-agent": UA } })).arrayBuffer());
  const name = crypto.createHash("sha256").update(u).digest("hex").slice(0, 16) + ".woff2";
  fs.writeFileSync(path.join(OUT, name), buf);
  css = css.split(u).join(`/fonts/${name}`);
}
fs.writeFileSync(path.join(CSS_OUT, "fonts.css"), `/* Generated by scripts/fetch-fonts.mjs from Google Fonts (SIL OFL 1.1). Do not edit. */\n${css}`);
console.log(`${urls.length} font files written to ${OUT}`);
