/**
 * Writes the SQL data migration that registers template "scrapbook" v1 with its default content
 * (generated from src/templates/scrapbook/defaults.ts so the DB and code can never drift), and
 * the V1 product. Run: npx tsx scripts/gen-template-migration.ts
 */
import fs from "node:fs";
import { newSiteContent } from "../src/templates/scrapbook/defaults";
import { SCHEMA_VERSION, draftContentSchema } from "../src/templates/scrapbook/schema";

const content = draftContentSchema.parse(newSiteContent());
const json = JSON.stringify(content).replace(/'/g, "''");
const sql = `-- Generated by scripts/gen-template-migration.ts — do not edit by hand.
insert into public.templates (key, name, description, sort)
values ('scrapbook', 'Scrapbook Surprise', 'Pink pastel scrapbook: envelope letter, polaroid memories, coupons, our-song player, cupcake wish and a final surprise.', 1)
on conflict (key) do nothing;

insert into public.template_versions (template_key, version, schema_version, default_content, is_current, notes)
values ('scrapbook', 1, ${SCHEMA_VERSION}, '${json}'::jsonb, true, 'Initial release (port of the original single-file experience).')
on conflict (template_key, version) do nothing;

-- V1 product. Price is editable from the admin dashboard (₹499.00 = 49900 paise).
insert into public.products (template_key, name, description, price_paise, currency, edit_days, live_days)
select 'scrapbook', 'Scrapbook Surprise — personal website', 'Your own private birthday website: 30 days to edit, live for 1 year.', 49900, 'INR', 30, 365
where not exists (select 1 from public.products where template_key = 'scrapbook');
`;
fs.writeFileSync("supabase/migrations/20261005000004_seed_scrapbook_template.sql", sql);
console.log("wrote supabase/migrations/20261005000004_seed_scrapbook_template.sql", json.length, "bytes of content");
